# Generated by Django 4.2.7 on 2023-12-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='долг перед поставщиком')),
                ('hierarchy_level', models.PositiveSmallIntegerField(verbose_name='уровень в иерархии')),
                ('node_type', models.CharField(choices=[('factory', 'Завод'), ('ie', 'ИП'), ('retail_network', 'Розничная сеть')], max_length=20, verbose_name='тип элемента сети')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наизменование продукта')),
                ('model', models.CharField(max_length=50, verbose_name='модель продукта')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics.networknode', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(blank=True, to='electronics.product', verbose_name='продукты'),
        ),
        migrations.AddField(
            model_name='networknode',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='electronics.networknode'),
        ),
    ]
